[package]
name = "envelopes"
version = "0.1.0"

[profile.dev]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
panic = 'unwind'

[[bin]]
name = "envelopes_rs"
path = "envelopes.rs"

[dependencies]
rand = "*"
